FROM python:3

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1

COPY data/data.json data/data.json
COPY sensor.py .

CMD [ "python", "sensor.py" ]
