version: "3.9"

services:
  metr-device-rabbitmq:
    container_name: metr-device-rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
      - 15692:15692
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data
    networks:
      - metr-network

  metr-device-gateway:
    container_name: metr-device-gateway
    build:
      context: .
      dockerfile: Dockerfile.gateway
    depends_on:
      - metr-device-rabbitmq
    links:
      - metr-device-rabbitmq
    networks:
      - metr-network

  metr-device-sensor:
    container_name: metr-device-sensor
    build:
      context: .
      dockerfile: Dockerfile.sensor
    depends_on:
      - metr-device-rabbitmq
    links:
      - metr-device-rabbitmq
    networks:
      - metr-network

volumes:
    rabbit_mqdata:
      driver: local

networks:
  metr-network:
    external: true
