down:
	docker-compose down

up-rabbitmq:
	docker-compose up metr-device-rabbitmq --build

up-consumer:
	docker-compose up metr-device-consumer --build

up-producer:
	docker-compose up metr-device-producer --build