# Generated by Django 4.2.2 on 2023-06-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_datetime', models.DateTimeField()),
                ('device_id', models.CharField(max_length=255)),
                ('device_manufacturer', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('device_version', models.CharField(max_length=255)),
                ('measurement_dimension', models.CharField(max_length=255)),
                ('measurement_value', models.IntegerField()),
                ('measurement_at_duedate', models.IntegerField()),
                ('duedate_datetime', models.DateTimeField()),
            ],
        ),
    ]
